# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/zingabory/gallery/models/category/fields.yaml

# Model Class name
modelClass: Zingabory\Gallery\Models\Category

# Default redirect location
defaultRedirect: zingabory/gallery/category

# Create page
create:
    title: Create Category
    redirect: zingabory/gallery/category/update/:id
    redirectClose: zingabory/gallery/category

# Update page
update:
    title: Edit Category
    redirect: zingabory/gallery/category
    redirectClose: zingabory/gallery/category

# Preview page
preview:
    title: Preview Category